// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOkGLAWnCeRRgR8rhIrKJMWvBTgEGU_c',
    appId: '1:479127977909:web:46ad35f6c096d92792a3fc',
    messagingSenderId: '479127977909',
    projectId: 'konnekt-31ce5',
    authDomain: 'konnekt-31ce5.firebaseapp.com',
    storageBucket: 'konnekt-31ce5.firebasestorage.app',
    measurementId: 'G-7N6G7D2S92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqrYefyAdRfs_h6BT7VEaUWFydAEADLek',
    appId: '1:479127977909:android:8f4860e47c4c26fa92a3fc',
    messagingSenderId: '479127977909',
    projectId: 'konnekt-31ce5',
    storageBucket: 'konnekt-31ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRJ1cugGtVtjvCpK--ChsniMoHgIXPJg',
    appId: '1:479127977909:ios:5db3abc75485e43892a3fc',
    messagingSenderId: '479127977909',
    projectId: 'konnekt-31ce5',
    storageBucket: 'konnekt-31ce5.firebasestorage.app',
    iosBundleId: 'com.example.konnekt',
  );

}